### ISSUE TITLE
Warning when applying function fitDelay.inla

### ISSUE THREAD

**Issue by claudia-codeco** [claudia-codeco/AlertTools#10]
Using fitDelay.inla with dengue data from city 2305100 produces the following warning:

*** WARNING *** Eigenvalue 1 of the Hessian is -1328.58 < 0
	*** WARNING *** Set this eigenvalue to 3.61325
	*** WARNING *** This have consequence for the accurancy of
	*** WARNING *** the approximations; please check!!!
	*** WARNING *** R-inla: Use option inla(..., control.inla = list(h = h.value), ...) 
	*** WARNING *** R-inla: to chose a different  `h.value'.

Should we care about that? The output seems ok.
The same happen with city 2303105

**Comment by marfcg** [comment]
This is usually the case for time series with low profile.
I'm currently ignoring it completely, but Leo might have a different opinion on the best approach.

It usually translates into broader confidence intervals.
