### ISSUE TITLE
MEM - Sao Jose do Rio Preto

### ISSUE THREAD

**Issue by claudia-codeco** [claudia-codeco/AlertTools#11]
@marfcg 
Eu apliquei mem para SJRP (SP) usando os argumentos default do info.dengue.apply.mem. Encontrei limiar_preseas = 176 e limiar_epidemico = 968. sao as linhas no grafico de incidencia abaixo. 
Voce não acha que ficaram muito altos? Ou é assim mesmo?
Se quiser rodar, é a cidade 3549805

![image](https://user-images.githubusercontent.com/4005254/35860397-0bc3904e-0b2b-11e8-89ab-3cae9d3acd0b.png)

**Comment by claudia-codeco** [comment]
Já resolvi, estava olhando para incidencia, e o que o mem retorna é em casos.

**Comment by claudia-codeco** [comment]
@marfcg
--
Só para ter certeza, os limiares gerados pela função info.dengue.apply.mem são casos ou incidencia?

**Comment by marfcg** [comment]
Conferi o código e ele escreve no banco os valores de incidência, sim. As colunas 'limiar_preseason', 'limiar_posseason', 'limiar_epidemico' são todas em termos de incidência.

Internamente, ele até gera colunas tanto em termos de casos quanto em termos de incidência, mas tanto o data.table de saída (quando solicitado) quanto a escrita no banco possuem apenas as colunas referentes a incidência.

**Comment by marfcg** [comment]
No caso de Ribeirão Preto, o que pode estar jogando o limiar epidêmico tão para cima são as temporadas de baixa atividade, pois elas afetam a estimativa da dispersão da distribuição de casos durante o período de atividade.
No caso dos dados de SRAG, resolvemos isso removendo as temporadas cuja atividade não ultrapassa o limiar preseason. Ou seja, calculamos com os dados completos, removemos as temporadas cujo ico ficou abaixo de limiar_preseason e recalculamos os limiares.
Isso em pouco altera o limiar pre/pos, pois eles são pouco sensíveis a isso, mas altera significativamente o limiar de atividade alta (limiar_epidemico).

No script para do info.dengue, isso não está sendo feito. Vou rodar com essa alteração e colocar aqui o gráfico para ilustração do resultado.

**Comment by marfcg** [comment]
Claudia,

Achei o gargalo. Nas internas da função ela não estava recebendo as opções que definem alguns parâmetros chave.
Arrumei o código e agora está devolvendo corretamente os valores como gerados ano passado para os demais municípios.

Fiz um pull request com as alterações.

Valores para SJRP (nicidência):
limiar_preseason = 119
limiar_posseason = 104
limiar_epidemico = 785
![ribeiraopreto](https://user-images.githubusercontent.com/8262366/35946164-e6bcee60-0c49-11e8-9138-f67020bc3903.png)

**Comment by claudia-codeco** [comment]
Otimo. Ainda assim, você não acha que está muito alto? O limiar pre-epidemico já está no meio da epidemia. Será que devemos baixar o percentil?

**Comment by marfcg** [comment]
Claudia,

Na última atualização do MEM que puxei para meu repositório (e que é utilizado aqui no alerta), alteraram o parâmetro default referente a estatística utilizada para estimar esses limiares.
Alterei nossas funções para utilizar, por padrão, o que vinhamos trabalhando antes.

Segue gráfico feito com o novo algoritmo para o Rio e para SJRP, para avaliação.
Se achares que agora está ok, faço um novo pull request com as alterações implementadas.

![riodejaneiro](https://user-images.githubusercontent.com/8262366/35979162-c8119846-0cce-11e8-82d1-4807f485dc27.png)

![saojosedoriopreto](https://user-images.githubusercontent.com/8262366/35979168-cd72ae24-0cce-11e8-8937-c05b15824378.png)

**Comment by claudia-codeco** [comment]
Sim ficou otimo assim!

obrigada,
bj

2018-02-08 12:52 GMT-02:00 Marcelo F C Gomes <notifications@github.com>:

**Comment by marfcg** [comment]
Feito, já está atualizado no pull request aberto.
