### ISSUE TITLE
Minor bug in episem function inside utility_tools.R

### ISSUE THREAD

**Issue by marfcg** [claudia-codeco/AlertTools#2]
[Line 70](https://github.com/claudia-codeco/AlertTools/blob/master/R/utility_tools.R#L70)
It should be strictly >, not >=
`if (x > ewd) fwd <- ewd + 1`

As it is, whenever YYYY-12-31 falls on a Saturday, the code will return SE (YYYY+1)01 for that day, instead of YYYY52 (or 53 depending on the year). Since this bug only presents itself when 12-31 is a Saturday, and it only returns the wrong SE for that particular day, it goes unnoticed most of the time.
Unfortunately, this is the case for 2016.

Example:
With the code as is, the date 2016-12-31 will return SE 201701, instead of 201652, as it should.
With the '>' relation, it will correctly return 201652. 

Cheers.

**Comment by claudia-codeco** [comment]
Agree, but it does not solve the whole problem. 
With the proposed modification, 2017-12-31 (domingo) returns 201753 instead of 201801 (correct)
